# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    xcode_select "/Applications/Xcode.app"
    bundle_install
  end

  desc "Apply version & build number"
  lane :vb do
    version_number = "1.0.2" # Change version number here
    build_number = "7" # Change build number here

    ensure_git_branch(branch: 'master')
    git_pull
    
    increment_version_number(
      version_number: version_number
    )

    increment_build_number(
      build_number: build_number
    )

    git_add(path: ".")
    version_string = version_number + "(" + build_number + ")"
    commit_message = "Version bump to " + version_string + " by Fastlane."
    git_commit(path: ".", message: commit_message)
    add_git_tag(tag: version_number + "/" + build_number)
  end

  private_lane :build_for_app_store do
    match(type: "appstore")
    gym(scheme: "Blahker",
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "com.elaborapp.Blahker" => "match AppStore com.elaborapp.Blahker",
          "com.elaborapp.Blahker.ContentBlocker" => "match AppStore com.elaborapp.Blahker.ContentBlocker"
        }
      },
      export_xcargs: '-allowProvisioningUpdates',
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :tf do
    build_for_app_store
    pilot(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :store do
    ensure_git_branch
    ensure_git_status_clean
    build_for_app_store
    pilot(skip_waiting_for_build_processing: true)
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
